# syntax=docker/dockerfile:1
FROM golang:1.23-bookworm AS dev
WORKDIR /src
RUN go install github.com/air-verse/air@v1.61.7
COPY go.mod go.sum* ./
RUN go mod download
COPY . .
CMD ["air", "-c", ".air.toml"]
